// Mapping des portraits - Généré automatiquement
const portraitsMapping = {
  "03-A-Kyo LV2": null,
  "A-Angel": "portraits_encyclopedia/A-Angel.sff",
  "ABYSS'Mega's": null,
  "ALBA MEIRA KOF XI -MI2": "portraits_encyclopedia/ALBA MEIRA KOF XI -MI2.gif",
  "Aika": "portraits_encyclopedia/Aika.sff",
  "Aika_MK": "portraits_encyclopedia/Aika_MK.sff",
  "Aileen": "portraits_encyclopedia/Aileen.sff",
  "Akari": "portraits_encyclopedia/Akari.sff",
  "Akiha Orochi": null,
  "Akiha Yagami": "portraits_encyclopedia/Akiha Yagami.sff",
  "Akiha Yagami DK": null,
  "Akiha Yagami1": "portraits_encyclopedia/Akiha Yagami1.png",
  "Akira_Kazakami": null,
  "Alfred_WLS": "portraits_encyclopedia/Alfred_WLS.png",
  "Alou_AKOF": "portraits_encyclopedia/Alou_AKOF.jpg",
  "Alter Kyo": null,
  "Amoumi-KOFM": null,
  "Andy-ROTD": "portraits_encyclopedia/Andy-ROTD.sff",
  "Aner Rolange KOFM": null,
  "Anette-KOFM": "portraits_encyclopedia/Anette-KOFM.sff",
  "AngusPurple-KOFM": null,
  "Another Scarlet": null,
  "Arctic Emperor": null,
  "Ash": "portraits_encyclopedia/Ash.bmp",
  "Athena": "portraits_encyclopedia/Athena.sff",
  "Athena Asamiya MI KOFM": null,
  "Athena-Heidern": "portraits_encyclopedia/Athena-Heidern.sff",
  "Athena_XI": "portraits_encyclopedia/Athena_XI.sff",
  "BLAKE V3-1.1": null,
  "BW-Meiling": null,
  "Balto-KOFM": null,
  "Beast Yeorin QS": "portraits_encyclopedia/Beast Yeorin QS.png",
  "Benimaru-Nikaido-STAR": null,
  "BlackPrincess_Tohka": "portraits_encyclopedia/BlackPrincess_Tohka.sff",
  "Boss Gustab M": null,
  "Business_Vanessa-KOFM": null,
  "C.Kyo.Blood-KOFM": null,
  "Carlin.Blood-CKOFM": null,
  "Caser.Yashiro": null,
  "Chalice": "portraits_encyclopedia/Chalice.sff",
  "Chaos-CKOFM": "portraits_encyclopedia/Chaos-CKOFM.png",
  "Chobi-Hige": null,
  "Choi_XI": "portraits_encyclopedia/Choi_XI.png",
  "Clone Blood Rugal": null,
  "Clone Zero": null,
  "Cronus": "portraits_encyclopedia/Cronus.sff",
  "Cruelty Sula UM": null,
  "D.Yashiro.Rhythm(Dusk)1.x": null,
  "D=Rockula": null,
  "DF-Sula": "portraits_encyclopedia/DF-Sula.sff",
  "DG.Rugal-KOFM": null,
  "D_DisciplineGirl": null,
  "Daiki_Final(Prototype)": "portraits_encyclopedia/Daiki_Final(Prototype).png",
  "Daisu": "portraits_encyclopedia/Daisu.sff",
  "Delirus": "portraits_encyclopedia/Delirus.sff",
  "Dragondomainlords": "portraits_encyclopedia/Dragondomainlords.sff",
  "Drakyola": "portraits_encyclopedia/Drakyola.sff",
  "Dual-flame_Magaki": null,
  "Duester": "portraits_encyclopedia/Duester.sff",
  "Element Ash": "portraits_encyclopedia/Element Ash.png",
  "Element Scarlet": null,
  "Element-Adel": null,
  "Eputh Blood-KOFM": "portraits_encyclopedia/Eputh Blood-KOFM.png",
  "Error Zero": null,
  "Essence of Darkness": "portraits_encyclopedia/Essence of Darkness.png",
  "Eve": "portraits_encyclopedia/Eve.sff",
  "Fang": "portraits_encyclopedia/Fang.sff",
  "Felix_THird": null,
  "Final Adel": "portraits_encyclopedia/Final Adel.sff",
  "Final Goeniko": "portraits_encyclopedia/Final Goeniko.sff",
  "Final Sachiel WF": "portraits_encyclopedia/Final Sachiel WF.png",
  "Final Zeroko B": "portraits_encyclopedia/Final Zeroko B.png",
  "Final-IGNIZ": null,
  "Final-OriginalZero": null,
  "Flamme(S)": null,
  "GARS": null,
  "GOD_ADEL(2012-01-28 Trial)": null,
  "Garnet 1.1": null,
  "Geese-KOFM": "portraits_encyclopedia/Geese-KOFM.sff",
  "God_Wind": "portraits_encyclopedia/God_Wind.sff",
  "Goktore-CKOFM": null,
  "Graves": "portraits_encyclopedia/Graves.sff",
  "HIEL-KOFM": null,
  "Hiel_SP": null,
  "Hiyoi": null,
  "Hunter_U6746": "portraits_encyclopedia/Hunter_U6746.sff",
  "Infernal_Wind": "portraits_encyclopedia/Infernal_Wind.gif",
  "K9999_KOF": null,
  "Kaneda-KOFM": "portraits_encyclopedia/Kaneda-KOFM.png",
  "Kaori Yumiko": "portraits_encyclopedia/Kaori Yumiko.sff",
  "Kartis": null,
  "Kasim_LV2-CKOFM[v0.40]": null,
  "Kasumi-KOFM": null,
  "Kei": null,
  "Kevenoce": null,
  "Keyser-Aunthmer": null,
  "Kotone": null,
  "Kyaga-KOFM": null,
  "Kychiel": "portraits_encyclopedia/Kychiel.sff",
  "LUMIEL": null,
  "Lane.Blood-CKOFM": null,
  "Littledevil-Phoenix": "portraits_encyclopedia/Littledevil-Phoenix.jpg",
  "Lord-Goenitz": null,
  "Magnus": "portraits_encyclopedia/Magnus.sff",
  "Mai Phoenix XI": null,
  "Maltet": "portraits_encyclopedia/Maltet.sff",
  "Maryl": "portraits_encyclopedia/Maryl.sff",
  "Matam": "portraits_encyclopedia/Matam.sff",
  "Meld_Boss": null,
  "N-Zeroko": "portraits_encyclopedia/N-Zeroko.sff",
  "Nao-MX 1.0": null,
  "NeoDio KOFM": null,
  "NeoGeegus KOFM": null,
  "Nero": "portraits_encyclopedia/Nero.png",
  "New_Kyouki": "portraits_encyclopedia/New_Kyouki.png",
  "Noa_MK": null,
  "Nox Bernstein": null,
  "O.Zero-Prominence": null,
  "Olivia": null,
  "Original Psyqhical": null,
  "Orochi Kyo WF": null,
  "Orochi Leona-KOFM": null,
  "Orochi-EV1.55": null,
  "Orochi.Yamazaki-CKOFM": null,
  "P-LEONA_ELEMENT": null,
  "Psyche_42-1.1": "portraits_encyclopedia/Psyche_42-1.1.gif",
  "Psyche_57-1.1": null,
  "R.S.P": null,
  "Raika": null,
  "Raisen.blood-KOFM": "portraits_encyclopedia/Raisen.blood-KOFM.png",
  "Rayno": "portraits_encyclopedia/Rayno.sff",
  "Reas-KOFM": "portraits_encyclopedia/Reas-KOFM.sff",
  "Reyna": "portraits_encyclopedia/Reyna.sff",
  "Rinne-RH": null,
  "Rocken": null,
  "Rose": "portraits_encyclopedia/Rose.sff",
  "Rozwel S.K (LEGIT)": null,
  "Rugal7th": null,
  "Ryuji": "portraits_encyclopedia/Ryuji.sff",
  "S_Infezione": null,
  "Samael": null,
  "Sasin": null,
  "Shadow-Dancer": "portraits_encyclopedia/Shadow-Dancer.sff",
  "Sonic Vanesa": null,
  "Spiritland Lords": "portraits_encyclopedia/Spiritland Lords.jpg",
  "Tenrou_Kunagi": null,
  "ThunderMiss.Shermie": null,
  "Titan_KOF": null,
  "True Iori X_KOF": null,
  "Unfailed Gustab": null,
  "Unleashesd God Kula": null,
  "Valmar Rugal": null,
  "Viper": "portraits_encyclopedia/Viper.sff",
  "VladRose": null,
  "Voltage Zeroko-Pre": null,
  "WatchTV": "portraits_encyclopedia/WatchTV.sff",
  "WhirlWind-Goenitz": "portraits_encyclopedia/WhirlWind-Goenitz.sff",
  "White DeathRaGeroous Version": null,
  "Wild.O.Yashiro": "portraits_encyclopedia/Wild.O.Yashiro.sff",
  "Wind_MMXIX": "portraits_encyclopedia/Wind_MMXIX.sff",
  "Xion-V": "portraits_encyclopedia/Xion-V.sff",
  "Yamazaki.Blood": null,
  "Yukida": "portraits_encyclopedia/Yukida.sff",
  "Yuno-KOFM": "portraits_encyclopedia/Yuno-KOFM.sff",
  "Yuri_SV": null,
  "Zerozuchi_Boss": null,
  "_ArchiMurderer": null,
  "ai": null,
  "akuma": null,
  "asura-kofa": null,
  "baiyi": "portraits_encyclopedia/baiyi.sff",
  "billy": "portraits_encyclopedia/billy.bmp",
  "bob": "portraits_encyclopedia/bob.sff",
  "boss-orochi": null,
  "ccihinako": null,
  "ccijhun": null,
  "cciking": null,
  "ccishermie": null,
  "clone benimaru": null,
  "dr-yang-kofa": null,
  "final-goenitz": null,
  "god_orochi": null,
  "heraclius": "portraits_encyclopedia/heraclius.sff",
  "kfm": "portraits_encyclopedia/kfm.sff",
  "meteoricmarisa": "portraits_encyclopedia/meteoricmarisa.sff",
  "mizore-kofmLV2": null,
  "orochi-iori": null,
  "orochi-kyoko": null,
  "robo-kyo-kofa": null,
  "vandals": "portraits_encyclopedia/vandals.sff",
};
